### ISSUE TITLE
bug: json_exporter unable to download artifacts from github release / `get checksum list` fails 

### ISSUE THREAD

**Issue by copolycube** [bodsch/ansible-collection-prometheus#15]
It started to fail since a few days.
##### SUMMARY

` msg: An error has occurred. Please check the availability of prometheus-community/json_exporter and version v0.6.0 at Github!`

```
TASK [bodsch.prometheus.json_exporter : detect the downloaded json_exporter archive] ***
Monday 09 June 2025  18:08:17 +0000 (0:00:00.187)       0:01:15.900 *********** 
Monday 09 June 2025  18:08:17 +0000 (0:00:00.187)       0:01:15.900 *********** 
ok: [target -> localhost]
TASK [bodsch.prometheus.json_exporter : get checksum list] *********************
Monday 09 June 2025  18:08:18 +0000 (0:00:00.191)       0:01:16.092 *********** 
Monday 09 June 2025  18:08:18 +0000 (0:00:00.191)       0:01:16.091 *********** 
fatal: [target -> localhost]: FAILED! => changed=false 
  checksum: null
  checksums: []
  msg: An error has occurred. Please check the availability of prometheus-community/json_exporter and version v0.6.0 at Github!
TASK [bodsch.prometheus.json_exporter : delete download directory] *************
Monday 09 June 2025  18:08:19 +0000 (0:00:00.893)       0:01:16.985 *********** 
Monday 09 June 2025  18:08:19 +0000 (0:00:00.893)       0:01:16.984 *********** 
changed: [target -> localhost]
TASK [bodsch.prometheus.json_exporter : exit with fail] ************************
Monday 09 June 2025  18:08:19 +0000 (0:00:00.210)       0:01:17.195 *********** 
Monday 09 June 2025  18:08:19 +0000 (0:00:00.210)       0:01:17.194 *********** 
fatal: [target]: FAILED! => changed=false 
  msg: A serious error occurred when downloading the archive.
PLAY RECAP *********************************************************************
target               : ok=15   changed=3    unreachable=0    failed=1    skipped=3    rescued=1    ignored=0   
Playbook run took 0 days, 0 hours, 1 minutes, 17 seconds
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Monitoring collector - setup prometheus json_exporter only
  hosts: label_monitoring_server
  vars:
    become_user: root
    become: true

  roles:
    # json_exporter role from bodsch.prometheus (no community role available)
    # https://github.com/bodsch/ansible-collection-prometheus/blob/main/roles/json_exporter/README.md
    - role: bodsch.prometheus.json_exporter
      become: true
      vars:
        json_exporter_service:
          log:
            level: "info"
          web:
            listen_address: "0.0.0.0:7979"
        json_exporter_version: '0.7.0'
```

<details><summary>previous version / depdecated invocation of json_exporter</summary>
<p>

```yaml

  roles:
    # json_exporter role from bodsch.prometheus (no community role available)
    # https://github.com/bodsch/ansible-collection-prometheus/blob/main/roles/json_exporter/README.md
    - role: bodsch.prometheus.json_exporter
      become: yes
      vars:
        prometheus_json_exporter_version: 0.20.0
        prometheus_json_exporter_opts:
          log_level: "info"
        prometheus_json_exporter_web_listen_address: 0.0.0.0:7979
        prometheus_json_exporter_web_telemetry_path: '/probe'
```

</p>
</details> 

##### EXPECTED RESULTS

```paste below

```

##### ACTUAL RESULTS

```paste below
  msg: An error has occurred. Please check the availability of prometheus-community/json_exporter and version v0.6.0 at Github!
```

##### ENVIRONMENT

```
ansible -m setup -a 'filter=ansible_architecture,ansible_system' localhost
[WARNING]: No inventory was parsed, only implicit localhost is available
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_architecture": "x86_64",
        "ansible_system": "Linux"
    },
    "changed": false
}
```

**Comment by copolycube** [comment]
The error message is triggered in  https://github.com/bodsch/ansible-collection-prometheus/blob/main/roles/json_exporter/tasks/download.yml but I did not figured out what and where something went wrong since june 8th.

**Comment by copolycube** [comment]
This error started after 
https://github.com/bodsch/ansible-collection-scm/commit/93897125b0e281600bdaae454cef284b5aa8852b was merged

**Comment by copolycube** [comment]
Edit on how to reproduce, I had leftover code from previous upgrade, and I split the json_exporter install in it's own playbook to keep my CI cleaner while this is commented out

```
---
- name: Monitoring collector - setup prometheus json_exporter only
  hosts: label_monitoring_server
  vars:
    become_user: root
    become: true

  roles:
    # json_exporter role from bodsch.prometheus (no community role available)
    # https://github.com/bodsch/ansible-collection-prometheus/blob/main/roles/json_exporter/README.md
    - role: bodsch.prometheus.json_exporter
      become: true
      vars:
        json_exporter_service:
          log:
            level: "info"
          web:
            listen_address: "0.0.0.0:7979"
        json_exporter_version: '0.7.0'
```
