### ISSUE TITLE
feat: json_exporter: allow templating of modules config

### ISSUE THREAD

**Issue by sleepy-nols** [bodsch/ansible-collection-prometheus#9]
##### SUMMARY

allow templating of the modules config in `templates/config.yml.j2` via an optional var. `json_exporter_config` should not be templated if own modules are being templated.

##### ADDITIONAL INFORMATION

I would like to optionaly template my own modules config. solves the problem of not being able to template own module config.

I would implement this if wanted :)
 

```yaml
json_exporter
```

**Comment by bodsch** [comment]
Can you please give me an example (configurtion, template)?

**Comment by sleepy-nols** [comment]
Alright here are some examples. I quickly tested it and there are some templating quirks that do not quite match, but I suspect the `to_nice_yaml` filter on that.

config.yml.j2:
```yml
#jinja2: trim_blocks: True, lstrip_blocks: True
---
# {{ ansible_managed }}

{% if json_exporter_modules.keys() | length > 0 %}
modules:
  {{ json_exporter_modules | to_nice_yaml(indent=2,sort_keys=True) | indent(2, False) }}
{% endif %}

{% if (json_exporter_config is defined) and
      (json_exporter_config | count > 0) and
      (json_exporter_modules.keys() | length <= 0) %}
modules:
  default:
    metrics:
      {{ json_exporter_config | to_nice_yaml(indent=2,sort_keys=False) | indent(6, False) }}
{% endif %}

```

example dict:
```yml
json_exporter_modules:
  jellyfin:
    headers:
      Authorization: MediaBrowser Token=xxxxxxxxxxxxxxxxx
      Content-Type: application/json
      accept: application/json

    metrics:
      - name: jellyfin
        type: object
        help: User playback metrics from Jellyfin
        path: '{ [*] }'
        labels:
          user_name: '{ .UserName }'
          # User PromQL label_join and label_replace to concatenate
          # these values into a nice item description
          item_type: '{ .NowPlayingItem.Type }'
          item_name: '{ .NowPlayingItem.Name }'
          item_path: '{ .NowPlayingItem.Path }'
          series_name: '{ .NowPlayingItem.SeriesName }'
          episode_index: 'e{ .NowPlayingItem.IndexNumber }'
          season_index: 's{ .NowPlayingItem.ParentIndexNumber }'
          client_name: '{ .Client }'
          device_name: '{ .DeviceName }'
        values:
          is_paused: '{ .PlayState.IsPaused }'
```
